name: Publish

on: [push]

env:
  graalvm_version: '22.0.0.2'
  java_version: '17'
  branch: 'spring-native'

jobs:
  build:
    name: GraalVM - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: '${{ env.branch }}'
    - name: Set up GraalVM (Java ${{ env.java_version }})
      uses: graalvm/setup-graalvm@v1
      with:
        version: '${{ env.graalvm_version }}'
        java-version: '${{ env.java_version }}'
        components: 'native-image'

    - name: Set up swap space
      if: runner.os == 'Linux'
      uses: pierotofy/set-swap-space@v1.0
      with:
        swap-size-gb: 16
  
    - name: Adjust vm.swappiness
      run: sudo sysctl vm.swappiness=10

    - name: Build native images
      run: ./mvnw -B -ntp package -Pnative,prod -DskipTests
